### ISSUE TITLE
<strong> Not Rendering

### ISSUE THREAD

**Issue by RichieMcMullen** [mewebstudio/Purifier#79]
This tag wont render as bold for some reason. Any fix for this ?

**Comment by stayallive** [comment]
@RichieMcMullen unless I am incorrect it this seems to be related to browser rendering & HTML markup in general, this library has nothing to do with that except allowing a user to create a <strong> tag. If that tag is visible in the HTML source your purifier rules allowed it and is it to the browser to render it. 

Please see:
- https://stackoverflow.com/questions/6813750/any-ideas-why-strong-tag-doesnt-work-but-css-does
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#Usage_notes

But do make sure you have a <strong> tag in the html outputed by purifier, otherwise your rules are stripping the strong tag completely (and therefore not rendering bold).

**Comment by RichieMcMullen** [comment]
Ah, my fault. I'm using a Materialise CSS framework. The framework was overriding the `<strong>` tag with `font-weight: 300`

Problem solved. Thank you for your reply @stayallive
